sudo: required

services:
  - docker

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

before_install:
  - docker pull "$IMAGE"
  - wget https://raw.githubusercontent.com/essentialkaos/perfecto/master/perfecto-docker
  - wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.2/hadolint-Linux-x86_64
  - chmod +x perfecto-docker hadolint
  - ./hadolint --version

script:
  - ./perfecto-docker webkaos.spec
  - ./hadolint centos7.docker
