sudo: required

services:
  - docker

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

before_install:
  - docker pull "$IMAGE"
  - wget https://raw.githubusercontent.com/essentialkaos/perfecto/master/perfecto-docker
  - chmod +x perfecto-docker

script:
  - ./perfecto-docker webkaos.spec
