#!/bin/bash

################################################################################

main() {
  local opt

  for opt in "$@" ; do
    case "$opt" in
      "-v" | "-V" | "-h" | "-?")
        /usr/sbin/webkaos "$@" 2>&1 | sed '1!b;s/webkaos/nginx/g' 1>&2
        exit 0 ;;
    esac
  done

  /usr/sbin/webkaos "$@"
}

################################################################################

main "$@"
